# Generated by cpputils-cmake.
include /home/vint/projects/theta-linux/src/build/CMakeFiles/ThetaLinux.dir/flags.make
.PHONY: check-syntax
check-syntax:
	${CXX} -o /dev/null ${CXX_FLAGS} ${CXX_DEFINES} ${CXX_INCLUDES} -I/usr/src/linux/include -DNDEBUG -S ${CHK_SOURCES}